#!/bin/sh
source ../common.sh

# Check nvm isn't already loaded
nvm --version && die "nvm is already loaded"

# Load zsh-nvm
load_zsh_nvm

# Check nvm is now loaded
nvm --version || die "nvm wasn't loaded"
